module M2yLkr
  COMPANIES_PATH = "/companies"
  LOGIN_PATH = "/login"
  PASSWORD_PATH = "/password"
  DOCUMENT_PATH = "/document"
  EMAIL_PATH = "/email"
  MAIL_PATH = "/mail"
  ACCOUNTS_PATH = "/accounts"
  ADDRESSES_PATH = "/addresses"
  CARDS_PATH = "/card"
  NEW_PATH = "/new"
  CANCEL_PATH = "/cancel"
  TRANSFERS_PATH = "/linktransfers"
  LINKS_PATH = "/links"
  BILLETS_PATH = "/billets"
  INVOICE_PATH = "/invoice"
  PDF_PATH = "/pdf"
  STATUS_PATH = "/status"
  CNPJ_PATH = "/cnpj"
  CONTACT_PATH = "/contact"
  CREATE_PATH = "/create"
  RECHARGE_PATH = "/recharge"
end
